<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticleTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('articles')->insert([
            ['id' => 1, 'user_id' => 2, 'category_id' => 1, 'title' => 'Pantai Pink', 'description' => 'Wisata Pantai Pink Lombok, mempunyai karakteristik yang luar biasa. Pantai ini mempunyai pasir berwarna pink. Sebuah hal yang sangat langka di dunia. Hal inilah yang menyedot keinginan wisatawan seluruh dunia untuk mengunjungi pantai di lombok timur ini. Nama Pantai Pink sebenarnya hanya nama julukan. Pantai ini aslinya bernama Pantai Tangsi. Namun karena pasir mempunyai warna pink, jadilah pantai ini lebih populer dengan sebutan Pantai Pink. Sebenarnya pasir pantai cantik ini berwarna putih. Sedangkan warna pink muncul akibat percampuran pasir dengan butiran terumbu karang yang bertekstur halus. Butiran terumbu karang tersebut memiliki warna merah, sehingga membuat pasir berubah menjadi warna pink. Warna pink terlihat jelas ketika pasir terkena basah oleh ombak laut. Hamparan bukit yang mengelilingi Pantai membuat kecantikan pantai ini semakin bertambah sempurna. Pada bagian kiri pantai terdapat bukit dengan padang rumput hijau yang luas terhampar. Di atas bukit inilah pemandangan Pantai akan tampak lebih menawan dan menakjubkan.', 'image' => 'pantaipink.jpg'],
            ['id' => 2, 'user_id' => 2, 'category_id' => 2, 'title' => 'Gunung Rinjani', 'description' => 'Selain punya pantai-pantai super cantik yang membuat orang malas pulang, Pulau Lombok di Nusa Tenggara Barat punya primadona lain yang membuat banyak wisatawan jatuh cinta. Primadona tersebut adalah Gunung Rinjani. Gunung Rinjani sering disebut sebagai wisata trekking terbaik di Asia Tenggara. Jika kamu pernah melihat keindahan Gunung Rinjani langsung dengan mata kepala sendiri, tentu kamu akan mengiyakan pendapat itu dengan sangat mudah. Gunung Rinjani adalah gunung yang komplit. Ia punya padang sabana cantik yang ditumbuhi bunda edelweis, ia juga punya pemandangan sunrise yang menawan. Dari semua keindahan yang ada di Gunung Rinjani, Danau Segara Anak adalah yang paling dicari. Danau yang berada di ketinggian 2.000 mdpl ini merupakan permata paling indah di Gunung Rinjani. Keindahan danau ini juga dapat kita saksikan dari puncak Rinjani. Yang unik dari Gunung Rinjani adalah keberadaan Gunung Barujari yang berada di tengah-tengah Danau Segara Anak. Gunung Barujari adalah gunung yang berada di atas gunung sehingga gunung ini sering disebut sebagai anaknya Gunung Rinjani', 'image' => 'gunungrinjani.jpg'],
            ['id' => 3, 'user_id' => 4, 'category_id' => 1, 'title' => 'Pantai Nihiwatu', 'description' => 'Pantai Nihiwatu yang berada di wilayah Sumba Barat, Provinsi Nusa Tenggara Timur (NTT) ini merupakan salah satu tujuan para surfer atau peselancar kelas dunia untuk mencoba keganasan ombak pantai tersebut. Bahkan para peselancar menjuluki pantai ini dengan sebutan God’s Left. Oleh karena itu, banyak wisatawan yang berasal dari luar negeri. Untuk dapat menikmati keindahan dan kedahsyatan ombak di Pantai Nihiwatu tidak sembarang orang yang dapat melakukannya, termasuk orang Sumba sendiri. Pantai Nihiwatu memang merupakan salah satu pantai yang mempunyai sifat privasi bagi kalangan tertentu. Hal ini memang terdengar sedikit aneh, tetapi itulah kenyataan yang berlaku untuk Pantai Nihiwatu. Terletak di arah 30 Km dari Kota Waikabubak, Kabupaten Sumba Barat, Provinsi Nusa Tenggara Timur (NTT), pantai ini memang mimiliki suasana yang sepi dan nyaman sehingga sangat cocok bagi yang ingin menyendiri dan menikmati suasana pantai. Hal ini disebabkan karena letak Pantai Nihiwatu jauh dari keramaian kota dan belum terjamah oleh industri – industri yang ada di Indonesia. Pantai Nihiwatu saat ini dikelola oleh sebuah resort internasional yang bernama Resort Nihiwatu. Tidak semua orang dapat bebas memasuki lokasi pantai ini, karena penjagaan yang sangat ketat. Hanya tamu Resort Nihiwatu saja yang diperbolehkan memasukinya. Jika anda ingin menikmati keindahan Pantai Nihiwatu, tentunya anda perlu memesan kamar untuk menginap di Resort Nihiwatu terlebih dahulu.', 'image' => 'pantainihiwatu.jpg'],
            ['id' => 4, 'user_id' => 4, 'category_id' => 3, 'title' => 'Danau Toba', 'description' => 'Danau Toba terletak di pegunungan Bukit Barisan, Sumatera Utara. Luasnya 1.145 kilometer persegi yang menjadikannya danau terluas se-Asia Tenggara dan luasnya lebih besar dari Singapura [716 km]. Danau Toba juga menjadi danau terluas di dunia yang terbentuk dari erupsi gunung berapi, dan masuk dalam daftar Guinness World Records. Latar belakang Danau Toba terbentuk karena letusan gunung berapi yang memuntahkan 2.800 km kubik material letusan, sehingga membuat kawah yang lambat laun dipenuhi air menjadi danau. Di tengah Danau Toba terdapat pulau bernama Samosir. Pulau tersebut sekiranya mendekati luas dari negara Singapura dan memiliki beberapa desa dengan wisata alam luar biasa, seperti pegunungan dan air terjun.', 'image' => 'danautoba.jpg'],
            ['id' => 5, 'user_id' => 5, 'category_id' => 4, 'title' => 'Sungai Kalibiru', 'description' => 'Selain Raja Ampat, Papua Barat juga memiliki destinasi wisata yang tidak kalah indah, yaitu Sungai Kalibiru. Walaupun berada di dalam hutan dan tergolong tersembunyi, namun sungai ini sangat alami dan juga mampu menghipnotis para wisatawan. Terlebih lagi, air sungainya yang berwarna biru dan suhu air yang dingin mampu memberikan kesegaran bagi siapa saja yang berenang di dalam sungai ini.', 'image' => 'kalibiru.jpg']
        ]);
    }
}
